version: 2

defaults: &defaults
  working_directory: /tmp/app
  docker:
    - image: cimg/node:20.2.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - yarn-v1-{{ .Branch }}
      #       - yarn-v1
      # - run:
      #     name: Install dependencies
      #     command: yarn install --immutable
      # - save_cache:
      #     key: yarn-v1-{{ .Branch }}-{{ epoch }}
      #     paths:
      #       - .yarn/cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      # - run:
      #     name: Run linters
      #     command: |
      #       yarn lint
      #       yarn dedupe -c

  pre-publish:
    <<: *defaults
    docker:
      - image: alpine/git
    steps:
      - run:
          name: Set container destination
          command: |
            touch .destination
            if git describe --exact-match HEAD > /dev/null 2>&1; then
              echo "--destination ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)" | tee .destination
            else
              echo "--no-push" | tee .destination
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-publish:
    <<: *defaults
    docker:
      - image: gcr.io/kaniko-project/executor:v1.17.0-debug
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build container image
          # TODO cache?
          command: |
            echo '{"auths":{"ghcr.io":{"username":"markormesher","password":"${GHCR_PUBLISH_TOKEN}"}}}' > /kaniko/.docker/config.json
            /kaniko/executor \
              --cache \
              --cache-repo ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME} \
              --context dir:///tmp/app \
              --ignore-path /tmp/app \
              $(cat .destination)

workflows:
  version: 2
  main:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - pre-publish:
          requires:
            - setup
      - build-publish:
          requires:
            - pre-publish
            - lint
